### ISSUE TITLE
FFXI player kefkaesque missing friend Valok

### ISSUE THREAD

**Issue by dhufford81** [ValokAsura/WindowerAddons#5]
Valok,

Please talk to me, reconsider coming back to the game. I have progressed so far and learned so much. If you come back I promise it will be fun! I still use magicassistant every single day! You will be amazed! All the things that seemed out of reach before I can help you obtain!

**Comment by ValokAsura** [comment]
Is now too late? =) I'm sorry I vanished from the earth for a while. I was thinking about giving it another go but wanted to see if you were still around first.

**Comment by dhufford81** [comment]
Hey dude,

I do still play though I haven't been very active lately. I've been kinda
busy so I've been letting my computer mine for Ethereum lol. I'll
definitely be more active as the cold weather sets in. They just announced
all new job progression system that's like job points 2.0 so that will
bring a lot of people back. There's a bunch of new content too. I've got
like 6 jobs at best in slot for the most part several remas lol. You can
check my progress on a character search at ffxiah.com.

**Comment by ValokAsura** [comment]
Add me on Discord VoiD#7859.  I was going to reactivate right after messaging you but then I promptly got Covid and began feeling pretty terrible.

I'm at about 70% so I've finally resubscribed and I'm trying to get all of my settings and memories back into place. Lots of learning to do again.

**Comment by dhufford81** [comment]
I just added you on discord

Regards,
Dustin Hufford
DLH Technology
573.864.4479
